# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170828_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='password',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='username',
        ),
        migrations.DeleteModel(
            name='Firm',
        ),
    ]
