# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170830_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='brands',
        ),
        migrations.AlterField(
            model_name='detail',
            name='nip',
            field=models.CharField(default=1234567, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.CharField(default=1234567, max_length=16),
            preserve_default=False,
        ),
    ]
