# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_brands_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company', models.ManyToManyField(to='users.Detail')),
            ],
        ),
    ]
