# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_favoriteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
